name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install poetry
      run: |
        pipx install poetry==2.0.0

    - name: Install dependencies
      run: |
        poetry install

    - name: Run linting
      run: |
        pylint *

    - name: Run type checking
      run: |
        mypy src/

    - name: Run tests and coverage
      run: |
        coverage run -m pytest
        coverage report